name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Test
      run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...

    - name: Run Revive linter
      uses: docker://morphy/revive-action:v2
